export const COUNTRIES = [
  { title: "Afghanistan", value: "AF" },
  { title: "Afrique du Sud", value: "ZA" },
  { title: "Albanie", value: "AL" },
  { title: "Algérie", value: "DZ" },
  { title: "Allemagne", value: "DE" },
  { title: "Andorre", value: "AD" },
  { title: "Angola", value: "AO" },
  { title: "Anguilla", value: "AI" },
  { title: "Antarctique", value: "AQ" },
  { title: "Antigua-et-Barbuda", value: "AG" },
  { title: "Arabie saoudite", value: "SA" },
  { title: "Argentine", value: "AR" },
  { title: "Arménie", value: "AM" },
  { title: "Aruba", value: "AW" },
  { title: "Australie", value: "AU" },
  { title: "Autriche", value: "AT" },
  { title: "Azerbaïdjan", value: "AZ" },
  { title: "Bahamas", value: "BS" },
  { title: "Bahreïn", value: "BH" },
  { title: "Bangladesh", value: "BD" },
  { title: "Barbade", value: "BB" },
  { title: "Bélarus", value: "BY" },
  { title: "Belgique", value: "BE" },
  { title: "Belize", value: "BZ" },
  { title: "Bénin", value: "BJ" },
  { title: "Bermudes", value: "BM" },
  { title: "Bhoutan", value: "BT" },
  { title: "Bolivie", value: "BO" },
  { title: "Bosnie-Herzégovine", value: "BA" },
  { title: "Botswana", value: "BW" },
  { title: "Brésil", value: "BR" },
  { title: "Brunéi Darussalam", value: "BN" },
  { title: "Bulgarie", value: "BG" },
  { title: "Burkina Faso", value: "BF" },
  { title: "Burundi", value: "BI" },
  { title: "Cambodge", value: "KH" },
  { title: "Cameroun", value: "CM" },
  { title: "Canada", value: "CA" },
  { title: "Cap-Vert", value: "CV" },
  { title: "Chili", value: "CL" },
  { title: "Chine", value: "CN" },
  { title: "Chypre", value: "CY" },
  { title: "Colombie", value: "CO" },
  { title: "Comores", value: "KM" },
  { title: "Congo-Brazzaville", value: "CG" },
  { title: "Corée du Nord", value: "KP" },
  { title: "Corée du Sud", value: "KR" },
  { title: "Costa Rica", value: "CR" },
  { title: "Côte d’Ivoire", value: "CI" },
  { title: "Croatie", value: "HR" },
  { title: "Cuba", value: "CU" },
  { title: "Danemark", value: "DK" },
  { title: "Djibouti", value: "DJ" },
  { title: "Dominique", value: "DM" },
  { title: "Égypte", value: "EG" },
  { title: "El Salvador", value: "SV" },
  { title: "Émirats arabes unis", value: "AE" },
  { title: "Équateur", value: "EC" },
  { title: "Érythrée", value: "ER" },
  { title: "Espagne", value: "ES" },
  { title: "Estonie", value: "EE" },
  { title: "État de la Cité du Vatican", value: "VA" },
  { title: "États fédérés de Micronésie", value: "FM" },
  { title: "États-Unis", value: "US" },
  { title: "Éthiopie", value: "ET" },
  { title: "Fidji", value: "FJ" },
  { title: "Finlande", value: "FI" },
  { title: "France", value: "FR" },
  { title: "Gabon", value: "GA" },
  { title: "Gambie", value: "GM" },
  { title: "Géorgie", value: "GE" },
  { title: "Géorgie du Sud et les îles Sandwich du Sud", value: "GS" },
  { title: "Ghana", value: "GH" },
  { title: "Gibraltar", value: "GI" },
  { title: "Grèce", value: "GR" },
  { title: "Grenade", value: "GD" },
  { title: "Groenland", value: "GL" },
  { title: "Guadeloupe", value: "GP" },
  { title: "Guam", value: "GU" },
  { title: "Guatemala", value: "GT" },
  { title: "Guernesey", value: "GG" },
  { title: "Guinée", value: "GN" },
  { title: "Guinée équatoriale", value: "GQ" },
  { title: "Guinée-Bissau", value: "GW" },
  { title: "Guyana", value: "GY" },
  { title: "Guyane française", value: "GF" },
  { title: "Haïti", value: "HT" },
  { title: "Honduras", value: "HN" },
  { title: "Hongrie", value: "HU" },
  { title: "Île Bouvet", value: "BV" },
  { title: "Île Christmas", value: "CX" },
  { title: "Île de l'Ascension", value: "AC" },
  { title: "Île de Man", value: "IM" },
  { title: "Île Norfolk", value: "NF" },
  { title: "Îles Åland", value: "AX" },
  { title: "Îles Caïmans", value: "KY" },
  { title: "Îles Canaries", value: "IC" },
  { title: "Îles Cocos - Keeling", value: "CC" },
  { title: "Îles Cook", value: "CK" },
  { title: "Îles Féroé", value: "FO" },
  { title: "Îles Heard et MacDonald", value: "HM" },
  { title: "Îles Malouines", value: "FK" },
  { title: "Îles Mariannes du Nord", value: "MP" },
  { title: "Îles Marshall", value: "MH" },
  { title: "Îles Mineures Éloignées des États-Unis", value: "UM" },
  { title: "Îles Salomon", value: "SB" },
  { title: "Îles Turks et Caïques", value: "TC" },
  { title: "Îles Vierges britanniques", value: "VG" },
  { title: "Îles Vierges des États-Unis", value: "VI" },
  { title: "Inde", value: "IN" },
  { title: "Indonésie", value: "ID" },
  { title: "Irak", value: "IQ" },
  { title: "Iran", value: "IR" },
  { title: "Irlande", value: "IE" },
  { title: "Islande", value: "IS" },
  { title: "Israël", value: "IL" },
  { title: "Italie", value: "IT" },
  { title: "Jamaïque", value: "JM" },
  { title: "Japon", value: "JP" },
  { title: "Jersey", value: "JE" },
  { title: "Jordanie", value: "JO" },
  { title: "Kazakhstan", value: "KZ" },
  { title: "Kenya", value: "KE" },
  { title: "Kirghizistan", value: "KG" },
  { title: "Kiribati", value: "KI" },
  { title: "Koweït", value: "KW" },
  { title: "Laos", value: "LA" },
  { title: "Lesotho", value: "LS" },
  { title: "Lettonie", value: "LV" },
  { title: "Liban", value: "LB" },
  { title: "Libéria", value: "LR" },
  { title: "Libye", value: "LY" },
  { title: "Liechtenstein", value: "LI" },
  { title: "Lituanie", value: "LT" },
  { title: "Luxembourg", value: "LU" },
  { title: "Macédoine", value: "MK" },
  { title: "Madagascar", value: "MG" },
  { title: "Malaisie", value: "MY" },
  { title: "Malawi", value: "MW" },
  { title: "Maldives", value: "MV" },
  { title: "Mali", value: "ML" },
  { title: "Malte", value: "MT" },
  { title: "Maroc", value: "MA" },
  { title: "Martinique", value: "MQ" },
  { title: "Maurice", value: "MU" },
  { title: "Mauritanie", value: "MR" },
  { title: "Mayotte", value: "YT" },
  { title: "Mexique", value: "MX" },
  { title: "Moldavie", value: "MD" },
  { title: "Monaco", value: "MC" },
  { title: "Mongolie", value: "MN" },
  { title: "Monténégro", value: "ME" },
  { title: "Montserrat", value: "MS" },
  { title: "Mozambique", value: "MZ" },
  { title: "Myanmar", value: "MM" },
  { title: "Namibie", value: "NA" },
  { title: "Nauru", value: "NR" },
  { title: "Népal", value: "NP" },
  { title: "Nicaragua", value: "NI" },
  { title: "Niger", value: "NE" },
  { title: "Nigéria", value: "NG" },
  { title: "Niue", value: "NU" },
  { title: "Norvège", value: "NO" },
  { title: "Nouvelle-Calédonie", value: "NC" },
  { title: "Nouvelle-Zélande", value: "NZ" },
  { title: "Oman", value: "OM" },
  { title: "Ouganda", value: "UG" },
  { title: "Ouzbékistan", value: "UZ" },
  { title: "Pakistan", value: "PK" },
  { title: "Palaos", value: "PW" },
  { title: "Panama", value: "PA" },
  { title: "Papouasie-Nouvelle-Guinée", value: "PG" },
  { title: "Paraguay", value: "PY" },
  { title: "Pays-Bas", value: "NL" },
  { title: "Pérou", value: "PE" },
  { title: "Philippines", value: "PH" },
  { title: "Pitcairn", value: "PN" },
  { title: "Pologne", value: "PL" },
  { title: "Polynésie française", value: "PF" },
  { title: "Porto Rico", value: "PR" },
  { title: "Portugal", value: "PT" },
  { title: "Qatar", value: "QA" },
  { title: "R.A.S. chinoise de Hong Kong", value: "HK" },
  { title: "R.A.S. chinoise de Macao", value: "MO" },
  { title: "République centrafricaine", value: "CF" },
  { title: "République démocratique du Congo", value: "CD" },
  { title: "République dominicaine", value: "DO" },
  { title: "République tchèque", value: "CZ" },
  { title: "Réunion", value: "RE" },
  { title: "Roumanie", value: "RO" },
  { title: "Royaume-Uni", value: "GB" },
  { title: "Russie", value: "RU" },
  { title: "Rwanda", value: "RW" },
  { title: "Sahara occidental", value: "EH" },
  { title: "Saint-Barthélémy", value: "BL" },
  { title: "Saint-Kitts-et-Nevis", value: "KN" },
  { title: "Saint-Marin", value: "SM" },
  { title: "Saint-Martin", value: "MF" },
  { title: "Saint-Pierre-et-Miquelon", value: "PM" },
  { title: "Saint-Vincent-et-les Grenadines", value: "VC" },
  { title: "Sainte-Hélène", value: "SH" },
  { title: "Sainte-Lucie", value: "LC" },
  { title: "Samoa", value: "WS" },
  { title: "Samoa américaines", value: "AS" },
  { title: "Sao Tomé-et-Principe", value: "ST" },
  { title: "Sénégal", value: "SN" },
  { title: "Serbie", value: "RS" },
  { title: "Seychelles", value: "SC" },
  { title: "Sierra Leone", value: "SL" },
  { title: "Singapour", value: "SG" },
  { title: "Slovaquie", value: "SK" },
  { title: "Slovénie", value: "SI" },
  { title: "Somalie", value: "SO" },
  { title: "Soudan", value: "SD" },
  { title: "Sri Lanka", value: "LK" },
  { title: "Suède", value: "SE" },
  { title: "Suisse", value: "CH" },
  { title: "Suriname", value: "SR" },
  { title: "Svalbard et Île Jan Mayen", value: "SJ" },
  { title: "Swaziland", value: "SZ" },
  { title: "Syrie", value: "SY" },
  { title: "Tadjikistan", value: "TJ" },
  { title: "Taïwan", value: "TW" },
  { title: "Tanzanie", value: "TZ" },
  { title: "Tchad", value: "TD" },
  { title: "Terres australes françaises", value: "TF" },
  { title: "Territoire britannique de l'océan Indien", value: "IO" },
  { title: "Territoire palestinien", value: "PS" },
  { title: "Thaïlande", value: "TH" },
  { title: "Timor oriental", value: "TL" },
  { title: "Togo", value: "TG" },
  { title: "Tokelau", value: "TK" },
  { title: "Tonga", value: "TO" },
  { title: "Trinité-et-Tobago", value: "TT" },
  { title: "Tristan da Cunha", value: "TA" },
  { title: "Tunisie", value: "TN" },
  { title: "Turkménistan", value: "TM" },
  { title: "Turquie", value: "TR" },
  { title: "Tuvalu", value: "TV" },
  { title: "Ukraine", value: "UA" },
  { title: "Union européenne", value: "EU" },
  { title: "Uruguay", value: "UY" },
  { title: "Vanuatu", value: "VU" },
  { title: "Venezuela", value: "VE" },
  { title: "Viêt Nam", value: "VN" },
  { title: "Wallis-et-Futuna", value: "WF" },
  { title: "Yémen", value: "YE" },
  { title: "Zambie", value: "ZM" },
  { title: "Zimbabwe", value: "ZW" },
];

export type SelectMenuOption = (typeof COUNTRIES)[number];
